#!/usr/bin/env node
/**
 * build.mjs — dsh-client-ui-autoknit browser-half bundler (dependency-free).
 *
 * DSH front-end client modules serve ONE self-contained bundle per plugin
 * (the file behind `exports["./client"]`). The factory `require` handed to a
 * bundle resolves ONLY platform seed words (react, ...) and module-graph rows
 * declared in `dsh.client.external` — there is NO relative-path branch. So the
 * source split across lib/*.js MUST be inlined into a single dist/client.js in
 * which the only remaining require() calls target platform seed words.
 *
 * This bundler is intentionally pure-node (no esbuild/rollup) so the plugin
 * package builds anywhere. Inputs are the CommonJS source files under lib/.
 *
 * Usage:
 *   node build.mjs          # writes dist/client.js
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));

/** CJS modules to inline, in dependency order (all siblings, no deps). */
const MODULES = [
  ['logic', 'lib/logic.js'],
  ['bridge', 'lib/data-bridge.js'],
  ['i18n', 'lib/i18n.js'],
  ['style', 'lib/style.js'],
];

/** Relative-require → inline variable name, as written in lib/client.js. */
const REL_REWRITE = {
  "require('./logic.js')": '__ak_logic',
  "require('./data-bridge.js')": '__ak_bridge',
  "require('./i18n.js')": '__ak_i18n',
  "require('./style.js')": '__ak_style',
};

function read(p) {
  return readFileSync(join(HERE, p), 'utf8');
}

/**
 * Wrap one CJS source file into an isolated closure that returns its exports.
 * Keeps the WHOLE source (including the `module.exports = {...}` trailer) so
 * the closure's own `module.exports` gets populated; every export the module
 * declares must land on that object. Only the leading `'use strict';` is
 * stripped (the factory body keeps running under the host's strictness).
 *
 * Earlier we truncated at `module.exports =`, which left the closure's
 * exports as an EMPTY `{}` — so `i18n.makeT` (and every other export) came
 * back undefined at runtime. Keep the assignment.
 */
function inlineModule(varName, source) {
  let body = source.replace(/^'use strict';\s*\n?/, '');
  return `var ${varName} = (function () {
  var module = { exports: {} };
  var exports = module.exports;
${body}
  return module.exports;
})();`;
}

/**
 * Extract the factory body from lib/client.js (between the braces of the
 * `function (require) {` passed to __ModuleLoader__.load) and rewrite the
 * relative requires to the inlined variable names. Keeps `require('react')`.
 */
function extractFactory(source) {
  const anchor = "window.__ModuleLoader__.load('dsh-client-ui-autoknit', function (require) {";
  const start = source.indexOf(anchor);
  if (start === -1) throw new Error('build: __ModuleLoader__.load anchor not found in lib/client.js');
  const bodyStart = start + anchor.length; // points at the opening '{'

  // Bracket match. Depth starts at 1 because bodyStart sits just after the
  // factory's opening brace (the `{` that closes `function (require) {`); the
  // matching `}` at depth 0 is the factory's closing brace. A naive brace
  // count is exact for this source: verified that no string literal contains
  // a brace (comments may carry stray quotes, which a quote-state machine
  // would choke on — a plain count cannot).
  let depth = 1;
  let i = bodyStart;
  while (i < source.length) {
    const ch = source[i];
    if (ch === '{') {
      depth += 1;
    } else if (ch === '}') {
      depth -= 1;
      if (depth === 0) break;
    }
    i += 1;
  }
  if (depth !== 0) throw new Error('build: unbalanced braces in lib/client.js');

  let body = source.slice(bodyStart + 1, i);
  for (const [from, to] of Object.entries(REL_REWRITE)) {
    if (!body.includes(from)) throw new Error(`build: expected relative require ${from} not found`);
    body = body.split(from).join(to);
  }
  return body;
}

function main() {
  mkdirSync(join(HERE, 'dist'), { recursive: true });
  const inlined = MODULES.map(([name, path]) => inlineModule('__ak_' + name, read(path))).join('\n');
  const factoryBody = extractFactory(read('lib/client.js'));
  const out = `/* dsh-client-ui-autoknit — browser half (bundled).
 * Generated by build.mjs from lib/*.js — do not edit by hand.
 * Self-contained: the only require() targets are platform seed words.
 */
window.__ModuleLoader__.load({
  id: "dsh-client-ui-autoknit",
  factory: function (require) {
    var module = { exports: {} };
    var exports = module.exports;
${inlined}
${factoryBody}
    return exports;
  }
});
`;
  writeFileSync(join(HERE, 'dist', 'client.js'), out);
  console.log(`build: wrote dist/client.js (${out.length} bytes)`);
}

main();
